#!/bin/sh

# paravelvnc
#
# Create a reversed VNC connection to a specified host.
#
# (C) Copyright 2011 Fred Gleason <fredg@paravelsystems.com>
#
#   $Id: paravelvnc,v 1.2 2013/03/27 18:36:17 cvs Exp $
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2 as
#   published by the Free Software Foundation.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public
#   License along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

USAGE="paravelvnc <hostname>"

#
# Process Arguments
#
if [ -z $1 ] ; then
    echo $USAGE
    exit 256
fi
HOSTNAME=$1

X11VNC_REVERSE_CONNECTION_NO_AUTH=1
x11vnc -nopw -connect $HOSTNAME
